/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeInterface_YzVideoView */

#ifndef _Included_nativeInterface_YzVideoView
#define _Included_nativeInterface_YzVideoView
#ifdef __cplusplus
extern "C" {
#endif
#undef nativeInterface_YzVideoView_NO_ID
#define nativeInterface_YzVideoView_NO_ID -1L
#undef nativeInterface_YzVideoView_VISIBLE
#define nativeInterface_YzVideoView_VISIBLE 0L
#undef nativeInterface_YzVideoView_INVISIBLE
#define nativeInterface_YzVideoView_INVISIBLE 4L
#undef nativeInterface_YzVideoView_GONE
#define nativeInterface_YzVideoView_GONE 8L
#undef nativeInterface_YzVideoView_DRAWING_CACHE_QUALITY_LOW
#define nativeInterface_YzVideoView_DRAWING_CACHE_QUALITY_LOW 524288L
#undef nativeInterface_YzVideoView_DRAWING_CACHE_QUALITY_HIGH
#define nativeInterface_YzVideoView_DRAWING_CACHE_QUALITY_HIGH 1048576L
#undef nativeInterface_YzVideoView_DRAWING_CACHE_QUALITY_AUTO
#define nativeInterface_YzVideoView_DRAWING_CACHE_QUALITY_AUTO 0L
#undef nativeInterface_YzVideoView_SCROLLBARS_INSIDE_OVERLAY
#define nativeInterface_YzVideoView_SCROLLBARS_INSIDE_OVERLAY 0L
#undef nativeInterface_YzVideoView_SCROLLBARS_INSIDE_INSET
#define nativeInterface_YzVideoView_SCROLLBARS_INSIDE_INSET 16777216L
#undef nativeInterface_YzVideoView_SCROLLBARS_OUTSIDE_OVERLAY
#define nativeInterface_YzVideoView_SCROLLBARS_OUTSIDE_OVERLAY 33554432L
#undef nativeInterface_YzVideoView_SCROLLBARS_OUTSIDE_INSET
#define nativeInterface_YzVideoView_SCROLLBARS_OUTSIDE_INSET 50331648L
#undef nativeInterface_YzVideoView_KEEP_SCREEN_ON
#define nativeInterface_YzVideoView_KEEP_SCREEN_ON 67108864L
#undef nativeInterface_YzVideoView_SOUND_EFFECTS_ENABLED
#define nativeInterface_YzVideoView_SOUND_EFFECTS_ENABLED 134217728L
#undef nativeInterface_YzVideoView_HAPTIC_FEEDBACK_ENABLED
#define nativeInterface_YzVideoView_HAPTIC_FEEDBACK_ENABLED 268435456L
#undef nativeInterface_YzVideoView_FOCUSABLES_ALL
#define nativeInterface_YzVideoView_FOCUSABLES_ALL 0L
#undef nativeInterface_YzVideoView_FOCUSABLES_TOUCH_MODE
#define nativeInterface_YzVideoView_FOCUSABLES_TOUCH_MODE 1L
#undef nativeInterface_YzVideoView_FOCUS_BACKWARD
#define nativeInterface_YzVideoView_FOCUS_BACKWARD 1L
#undef nativeInterface_YzVideoView_FOCUS_FORWARD
#define nativeInterface_YzVideoView_FOCUS_FORWARD 2L
#undef nativeInterface_YzVideoView_FOCUS_LEFT
#define nativeInterface_YzVideoView_FOCUS_LEFT 17L
#undef nativeInterface_YzVideoView_FOCUS_UP
#define nativeInterface_YzVideoView_FOCUS_UP 33L
#undef nativeInterface_YzVideoView_FOCUS_RIGHT
#define nativeInterface_YzVideoView_FOCUS_RIGHT 66L
#undef nativeInterface_YzVideoView_FOCUS_DOWN
#define nativeInterface_YzVideoView_FOCUS_DOWN 130L
#undef nativeInterface_YzVideoView_MEASURED_SIZE_MASK
#define nativeInterface_YzVideoView_MEASURED_SIZE_MASK 16777215L
#undef nativeInterface_YzVideoView_MEASURED_STATE_MASK
#define nativeInterface_YzVideoView_MEASURED_STATE_MASK -16777216L
#undef nativeInterface_YzVideoView_MEASURED_HEIGHT_STATE_SHIFT
#define nativeInterface_YzVideoView_MEASURED_HEIGHT_STATE_SHIFT 16L
#undef nativeInterface_YzVideoView_MEASURED_STATE_TOO_SMALL
#define nativeInterface_YzVideoView_MEASURED_STATE_TOO_SMALL 16777216L
#undef nativeInterface_YzVideoView_TEXT_ALIGNMENT_INHERIT
#define nativeInterface_YzVideoView_TEXT_ALIGNMENT_INHERIT 0L
#undef nativeInterface_YzVideoView_TEXT_ALIGNMENT_RESOLVED_DEFAULT
#define nativeInterface_YzVideoView_TEXT_ALIGNMENT_RESOLVED_DEFAULT 131072L
#undef nativeInterface_YzVideoView_IMPORTANT_FOR_ACCESSIBILITY_AUTO
#define nativeInterface_YzVideoView_IMPORTANT_FOR_ACCESSIBILITY_AUTO 0L
#undef nativeInterface_YzVideoView_IMPORTANT_FOR_ACCESSIBILITY_YES
#define nativeInterface_YzVideoView_IMPORTANT_FOR_ACCESSIBILITY_YES 1L
#undef nativeInterface_YzVideoView_IMPORTANT_FOR_ACCESSIBILITY_NO
#define nativeInterface_YzVideoView_IMPORTANT_FOR_ACCESSIBILITY_NO 2L
#undef nativeInterface_YzVideoView_OVER_SCROLL_ALWAYS
#define nativeInterface_YzVideoView_OVER_SCROLL_ALWAYS 0L
#undef nativeInterface_YzVideoView_OVER_SCROLL_IF_CONTENT_SCROLLS
#define nativeInterface_YzVideoView_OVER_SCROLL_IF_CONTENT_SCROLLS 1L
#undef nativeInterface_YzVideoView_OVER_SCROLL_NEVER
#define nativeInterface_YzVideoView_OVER_SCROLL_NEVER 2L
#undef nativeInterface_YzVideoView_SYSTEM_UI_FLAG_VISIBLE
#define nativeInterface_YzVideoView_SYSTEM_UI_FLAG_VISIBLE 0L
#undef nativeInterface_YzVideoView_SYSTEM_UI_FLAG_LOW_PROFILE
#define nativeInterface_YzVideoView_SYSTEM_UI_FLAG_LOW_PROFILE 1L
#undef nativeInterface_YzVideoView_SYSTEM_UI_FLAG_HIDE_NAVIGATION
#define nativeInterface_YzVideoView_SYSTEM_UI_FLAG_HIDE_NAVIGATION 2L
#undef nativeInterface_YzVideoView_SYSTEM_UI_FLAG_FULLSCREEN
#define nativeInterface_YzVideoView_SYSTEM_UI_FLAG_FULLSCREEN 4L
#undef nativeInterface_YzVideoView_SYSTEM_UI_FLAG_LAYOUT_STABLE
#define nativeInterface_YzVideoView_SYSTEM_UI_FLAG_LAYOUT_STABLE 256L
#undef nativeInterface_YzVideoView_SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
#define nativeInterface_YzVideoView_SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION 512L
#undef nativeInterface_YzVideoView_SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
#define nativeInterface_YzVideoView_SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN 1024L
#undef nativeInterface_YzVideoView_STATUS_BAR_HIDDEN
#define nativeInterface_YzVideoView_STATUS_BAR_HIDDEN 1L
#undef nativeInterface_YzVideoView_STATUS_BAR_VISIBLE
#define nativeInterface_YzVideoView_STATUS_BAR_VISIBLE 0L
#undef nativeInterface_YzVideoView_SYSTEM_UI_LAYOUT_FLAGS
#define nativeInterface_YzVideoView_SYSTEM_UI_LAYOUT_FLAGS 1536L
#undef nativeInterface_YzVideoView_FIND_VIEWS_WITH_TEXT
#define nativeInterface_YzVideoView_FIND_VIEWS_WITH_TEXT 1L
#undef nativeInterface_YzVideoView_FIND_VIEWS_WITH_CONTENT_DESCRIPTION
#define nativeInterface_YzVideoView_FIND_VIEWS_WITH_CONTENT_DESCRIPTION 2L
#undef nativeInterface_YzVideoView_SCREEN_STATE_OFF
#define nativeInterface_YzVideoView_SCREEN_STATE_OFF 0L
#undef nativeInterface_YzVideoView_SCREEN_STATE_ON
#define nativeInterface_YzVideoView_SCREEN_STATE_ON 1L
#undef nativeInterface_YzVideoView_SCROLLBAR_POSITION_DEFAULT
#define nativeInterface_YzVideoView_SCROLLBAR_POSITION_DEFAULT 0L
#undef nativeInterface_YzVideoView_SCROLLBAR_POSITION_LEFT
#define nativeInterface_YzVideoView_SCROLLBAR_POSITION_LEFT 1L
#undef nativeInterface_YzVideoView_SCROLLBAR_POSITION_RIGHT
#define nativeInterface_YzVideoView_SCROLLBAR_POSITION_RIGHT 2L
#undef nativeInterface_YzVideoView_LAYER_TYPE_NONE
#define nativeInterface_YzVideoView_LAYER_TYPE_NONE 0L
#undef nativeInterface_YzVideoView_LAYER_TYPE_SOFTWARE
#define nativeInterface_YzVideoView_LAYER_TYPE_SOFTWARE 1L
#undef nativeInterface_YzVideoView_LAYER_TYPE_HARDWARE
#define nativeInterface_YzVideoView_LAYER_TYPE_HARDWARE 2L
#undef nativeInterface_YzVideoView_STATE_ERROR
#define nativeInterface_YzVideoView_STATE_ERROR 1006L
#undef nativeInterface_YzVideoView_STATE_IDLE
#define nativeInterface_YzVideoView_STATE_IDLE 1000L
#undef nativeInterface_YzVideoView_STATE_PREPARING
#define nativeInterface_YzVideoView_STATE_PREPARING 1001L
#undef nativeInterface_YzVideoView_STATE_PREPARED
#define nativeInterface_YzVideoView_STATE_PREPARED 1002L
#undef nativeInterface_YzVideoView_STATE_PLAYING
#define nativeInterface_YzVideoView_STATE_PLAYING 1003L
#undef nativeInterface_YzVideoView_STATE_PAUSED
#define nativeInterface_YzVideoView_STATE_PAUSED 1004L
#undef nativeInterface_YzVideoView_STATE_PLAYBACK_COMPLETED
#define nativeInterface_YzVideoView_STATE_PLAYBACK_COMPLETED 1005L
#undef nativeInterface_YzVideoView_TMPC_OUT_OF_MEMORY
#define nativeInterface_YzVideoView_TMPC_OUT_OF_MEMORY 0L
#undef nativeInterface_YzVideoView_TMPC_NO_SOURCE_DEMUX
#define nativeInterface_YzVideoView_TMPC_NO_SOURCE_DEMUX 1L
#undef nativeInterface_YzVideoView_TMPC_MEDIA_SPEC_ERROR
#define nativeInterface_YzVideoView_TMPC_MEDIA_SPEC_ERROR 23L
#undef nativeInterface_YzVideoView_TMPC_NO_PLAY_OBJECT
#define nativeInterface_YzVideoView_TMPC_NO_PLAY_OBJECT 26L
#undef nativeInterface_YzVideoView_TMPC_TEMOBI_TIME_OUT
#define nativeInterface_YzVideoView_TMPC_TEMOBI_TIME_OUT 28L
#undef nativeInterface_YzVideoView_TMPC_NOTIFY_MEDIA_INFO
#define nativeInterface_YzVideoView_TMPC_NOTIFY_MEDIA_INFO 51L
#undef nativeInterface_YzVideoView_TMPC_START_BUFFER_DATA
#define nativeInterface_YzVideoView_TMPC_START_BUFFER_DATA 52L
#undef nativeInterface_YzVideoView_TMPC_PRE_START
#define nativeInterface_YzVideoView_TMPC_PRE_START 53L
#undef nativeInterface_YzVideoView_TMPC_PLAY_FINISH
#define nativeInterface_YzVideoView_TMPC_PLAY_FINISH 55L
#undef nativeInterface_YzVideoView_TMPC_START_PLAY
#define nativeInterface_YzVideoView_TMPC_START_PLAY 54L
#undef nativeInterface_YzVideoView_BUFFER_TIME
#define nativeInterface_YzVideoView_BUFFER_TIME 273L
#undef nativeInterface_YzVideoView_VIDEO_LAYOUT_ORIGIN
#define nativeInterface_YzVideoView_VIDEO_LAYOUT_ORIGIN 0L
#undef nativeInterface_YzVideoView_VIDEO_SCALE_FIT
#define nativeInterface_YzVideoView_VIDEO_SCALE_FIT 1L
#undef nativeInterface_YzVideoView_VIDEO_SCALE_FILL
#define nativeInterface_YzVideoView_VIDEO_SCALE_FILL 2L
/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeOnCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeOnCreate
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeOnResume
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeOnPause
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeOnStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeOnStop
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeSetSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeSetSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeTmpcStart
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeTmpcStart
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeTmpcPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeTmpcPause
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeTmpcResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeTmpcResume
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeTmpcStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeTmpcStop
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeTmpcGetBufTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nativeInterface_YzVideoView_nativeTmpcGetBufTime
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeTmpcGetPlayPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nativeInterface_YzVideoView_nativeTmpcGetPlayPos
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeTmpcGetLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nativeInterface_YzVideoView_nativeTmpcGetLength
  (JNIEnv *, jobject);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeTmpcSeek
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nativeInterface_YzVideoView_nativeTmpcSeek
  (JNIEnv *, jobject, jint);

/*
 * Class:     nativeInterface_YzVideoView
 * Method:    nativeTmpcVideoScale
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_nativeInterface_YzVideoView_nativeTmpcVideoScale
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
