/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeInterface_YzVideoView_YzOnInfoListener */

#ifndef _Included_nativeInterface_YzVideoView_YzOnInfoListener
#define _Included_nativeInterface_YzVideoView_YzOnInfoListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
