/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeInterface_SmoAdMultiPlay */

#ifndef _Included_nativeInterface_SmoAdMultiPlay
#define _Included_nativeInterface_SmoAdMultiPlay
#ifdef __cplusplus
extern "C" {
#endif
#undef nativeInterface_SmoAdMultiPlay_CLIP_MAX_LEVEL
#define nativeInterface_SmoAdMultiPlay_CLIP_MAX_LEVEL 16L
#undef nativeInterface_SmoAdMultiPlay_AD_MAX_LEVEL
#define nativeInterface_SmoAdMultiPlay_AD_MAX_LEVEL 16L
#undef nativeInterface_SmoAdMultiPlay_AD_TYPE_START
#define nativeInterface_SmoAdMultiPlay_AD_TYPE_START 1L
#undef nativeInterface_SmoAdMultiPlay_AD_TYPE_BUFFER
#define nativeInterface_SmoAdMultiPlay_AD_TYPE_BUFFER 2L
#undef nativeInterface_SmoAdMultiPlay_AD_TYPE_PAUSE
#define nativeInterface_SmoAdMultiPlay_AD_TYPE_PAUSE 3L
#undef nativeInterface_SmoAdMultiPlay_AD_TYPE_END
#define nativeInterface_SmoAdMultiPlay_AD_TYPE_END 4L
#undef nativeInterface_SmoAdMultiPlay_AD_SHOW_FULL
#define nativeInterface_SmoAdMultiPlay_AD_SHOW_FULL 1L
#undef nativeInterface_SmoAdMultiPlay_AD_SHOW_CENTER
#define nativeInterface_SmoAdMultiPlay_AD_SHOW_CENTER 2L
/*
 * Class:     nativeInterface_SmoAdMultiPlay
 * Method:    createSmoClient
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_nativeInterface_SmoAdMultiPlay_createSmoClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     nativeInterface_SmoAdMultiPlay
 * Method:    getSmoClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nativeInterface_SmoAdMultiPlay_getSmoClient
  (JNIEnv *, jobject, jint);

/*
 * Class:     nativeInterface_SmoAdMultiPlay
 * Method:    releaseSmoClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nativeInterface_SmoAdMultiPlay_releaseSmoClient
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
