/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeInterface_YzVideoView_YzOnCompletionListener */

#ifndef _Included_nativeInterface_YzVideoView_YzOnCompletionListener
#define _Included_nativeInterface_YzVideoView_YzOnCompletionListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
