/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeInterface_SmoAdMultiPlay_MultiPlayObj */

#ifndef _Included_nativeInterface_SmoAdMultiPlay_MultiPlayObj
#define _Included_nativeInterface_SmoAdMultiPlay_MultiPlayObj
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
