/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeInterface_YzVideoView_YzOnErrorListener */

#ifndef _Included_nativeInterface_YzVideoView_YzOnErrorListener
#define _Included_nativeInterface_YzVideoView_YzOnErrorListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
