package com.cmmobi.railwifi.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cmmobi.railwifi.dao.Passenger;
import com.cmmobi.railwifi.dao.HistoryOrderForm;
import com.cmmobi.railwifi.dao.TravelOrderInfo;
import com.cmmobi.railwifi.dao.Fav;
import com.cmmobi.railwifi.dao.PlayHistory;

import com.cmmobi.railwifi.dao.PassengerDao;
import com.cmmobi.railwifi.dao.HistoryOrderFormDao;
import com.cmmobi.railwifi.dao.TravelOrderInfoDao;
import com.cmmobi.railwifi.dao.FavDao;
import com.cmmobi.railwifi.dao.PlayHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig passengerDaoConfig;
    private final DaoConfig historyOrderFormDaoConfig;
    private final DaoConfig travelOrderInfoDaoConfig;
    private final DaoConfig favDaoConfig;
    private final DaoConfig playHistoryDaoConfig;

    private final PassengerDao passengerDao;
    private final HistoryOrderFormDao historyOrderFormDao;
    private final TravelOrderInfoDao travelOrderInfoDao;
    private final FavDao favDao;
    private final PlayHistoryDao playHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        passengerDaoConfig = daoConfigMap.get(PassengerDao.class).clone();
        passengerDaoConfig.initIdentityScope(type);

        historyOrderFormDaoConfig = daoConfigMap.get(HistoryOrderFormDao.class).clone();
        historyOrderFormDaoConfig.initIdentityScope(type);

        travelOrderInfoDaoConfig = daoConfigMap.get(TravelOrderInfoDao.class).clone();
        travelOrderInfoDaoConfig.initIdentityScope(type);

        favDaoConfig = daoConfigMap.get(FavDao.class).clone();
        favDaoConfig.initIdentityScope(type);

        playHistoryDaoConfig = daoConfigMap.get(PlayHistoryDao.class).clone();
        playHistoryDaoConfig.initIdentityScope(type);

        passengerDao = new PassengerDao(passengerDaoConfig, this);
        historyOrderFormDao = new HistoryOrderFormDao(historyOrderFormDaoConfig, this);
        travelOrderInfoDao = new TravelOrderInfoDao(travelOrderInfoDaoConfig, this);
        favDao = new FavDao(favDaoConfig, this);
        playHistoryDao = new PlayHistoryDao(playHistoryDaoConfig, this);

        registerDao(Passenger.class, passengerDao);
        registerDao(HistoryOrderForm.class, historyOrderFormDao);
        registerDao(TravelOrderInfo.class, travelOrderInfoDao);
        registerDao(Fav.class, favDao);
        registerDao(PlayHistory.class, playHistoryDao);
    }
    
    public void clear() {
        passengerDaoConfig.getIdentityScope().clear();
        historyOrderFormDaoConfig.getIdentityScope().clear();
        travelOrderInfoDaoConfig.getIdentityScope().clear();
        favDaoConfig.getIdentityScope().clear();
        playHistoryDaoConfig.getIdentityScope().clear();
    }

    public PassengerDao getPassengerDao() {
        return passengerDao;
    }

    public HistoryOrderFormDao getHistoryOrderFormDao() {
        return historyOrderFormDao;
    }

    public TravelOrderInfoDao getTravelOrderInfoDao() {
        return travelOrderInfoDao;
    }

    public FavDao getFavDao() {
        return favDao;
    }

    public PlayHistoryDao getPlayHistoryDao() {
        return playHistoryDao;
    }

}
