package com.cmmobi.railwifi.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PASSENGER.
 */
public class Passenger {

    private Long id;
    private String user_id;
    /** Not-null value. */
    private String uuid;
    private String nick_name;
    private String telephone;
    private String birther;
    private String sex;
    private String head_path;

    public Passenger() {
    }

    public Passenger(Long id) {
        this.id = id;
    }

    public Passenger(Long id, String user_id, String uuid, String nick_name, String telephone, String birther, String sex, String head_path) {
        this.id = id;
        this.user_id = user_id;
        this.uuid = uuid;
        this.nick_name = nick_name;
        this.telephone = telephone;
        this.birther = birther;
        this.sex = sex;
        this.head_path = head_path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /** Not-null value. */
    public String getUuid() {
        return uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getBirther() {
        return birther;
    }

    public void setBirther(String birther) {
        this.birther = birther;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getHead_path() {
        return head_path;
    }

    public void setHead_path(String head_path) {
        this.head_path = head_path;
    }

}
