package com.cmmobi.railwifi.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECEIPT_ADDR.
 */
public class ReceiptAddr {

    private Long id;
    private String name;
    private String place;
    private String addr;
    private String tel;
    private String code;

    public ReceiptAddr() {
    }

    public ReceiptAddr(Long id) {
        this.id = id;
    }

    public ReceiptAddr(Long id, String name, String place, String addr, String tel, String code) {
        this.id = id;
        this.name = name;
        this.place = place;
        this.addr = addr;
        this.tel = tel;
        this.code = code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPlace() {
        return place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public String getAddr() {
        return addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

}
