package com.etoc.weflow.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACCOUNT_INFO.
 */
public class AccountInfo {

    /** Not-null value. */
    private String tel;
    private String userid;
    private String flowcoins;
    private String isregistration;
    private String makeflow;
    private String useflow;
    private String nickname;

    public AccountInfo() {
    }

    public AccountInfo(String tel) {
        this.tel = tel;
    }

    public AccountInfo(String tel, String userid, String flowcoins, String isregistration, String makeflow, String useflow, String nickname) {
        this.tel = tel;
        this.userid = userid;
        this.flowcoins = flowcoins;
        this.isregistration = isregistration;
        this.makeflow = makeflow;
        this.useflow = useflow;
        this.nickname = nickname;
    }

    /** Not-null value. */
    public String getTel() {
        return tel;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getFlowcoins() {
        return flowcoins;
    }

    public void setFlowcoins(String flowcoins) {
        this.flowcoins = flowcoins;
    }

    public String getIsregistration() {
        return isregistration;
    }

    public void setIsregistration(String isregistration) {
        this.isregistration = isregistration;
    }

    public String getMakeflow() {
        return makeflow;
    }

    public void setMakeflow(String makeflow) {
        this.makeflow = makeflow;
    }

    public String getUseflow() {
        return useflow;
    }

    public void setUseflow(String useflow) {
        this.useflow = useflow;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

}
