package com.etoc.weflow.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.etoc.weflow.dao.FrequentPhone;
import com.etoc.weflow.dao.FrequentQQ;
import com.etoc.weflow.dao.DownloadHistory;
import com.etoc.weflow.dao.AccountInfo;
import com.etoc.weflow.dao.MyMessage;

import com.etoc.weflow.dao.FrequentPhoneDao;
import com.etoc.weflow.dao.FrequentQQDao;
import com.etoc.weflow.dao.DownloadHistoryDao;
import com.etoc.weflow.dao.AccountInfoDao;
import com.etoc.weflow.dao.MyMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig frequentPhoneDaoConfig;
    private final DaoConfig frequentQQDaoConfig;
    private final DaoConfig downloadHistoryDaoConfig;
    private final DaoConfig accountInfoDaoConfig;
    private final DaoConfig myMessageDaoConfig;

    private final FrequentPhoneDao frequentPhoneDao;
    private final FrequentQQDao frequentQQDao;
    private final DownloadHistoryDao downloadHistoryDao;
    private final AccountInfoDao accountInfoDao;
    private final MyMessageDao myMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        frequentPhoneDaoConfig = daoConfigMap.get(FrequentPhoneDao.class).clone();
        frequentPhoneDaoConfig.initIdentityScope(type);

        frequentQQDaoConfig = daoConfigMap.get(FrequentQQDao.class).clone();
        frequentQQDaoConfig.initIdentityScope(type);

        downloadHistoryDaoConfig = daoConfigMap.get(DownloadHistoryDao.class).clone();
        downloadHistoryDaoConfig.initIdentityScope(type);

        accountInfoDaoConfig = daoConfigMap.get(AccountInfoDao.class).clone();
        accountInfoDaoConfig.initIdentityScope(type);

        myMessageDaoConfig = daoConfigMap.get(MyMessageDao.class).clone();
        myMessageDaoConfig.initIdentityScope(type);

        frequentPhoneDao = new FrequentPhoneDao(frequentPhoneDaoConfig, this);
        frequentQQDao = new FrequentQQDao(frequentQQDaoConfig, this);
        downloadHistoryDao = new DownloadHistoryDao(downloadHistoryDaoConfig, this);
        accountInfoDao = new AccountInfoDao(accountInfoDaoConfig, this);
        myMessageDao = new MyMessageDao(myMessageDaoConfig, this);

        registerDao(FrequentPhone.class, frequentPhoneDao);
        registerDao(FrequentQQ.class, frequentQQDao);
        registerDao(DownloadHistory.class, downloadHistoryDao);
        registerDao(AccountInfo.class, accountInfoDao);
        registerDao(MyMessage.class, myMessageDao);
    }
    
    public void clear() {
        frequentPhoneDaoConfig.getIdentityScope().clear();
        frequentQQDaoConfig.getIdentityScope().clear();
        downloadHistoryDaoConfig.getIdentityScope().clear();
        accountInfoDaoConfig.getIdentityScope().clear();
        myMessageDaoConfig.getIdentityScope().clear();
    }

    public FrequentPhoneDao getFrequentPhoneDao() {
        return frequentPhoneDao;
    }

    public FrequentQQDao getFrequentQQDao() {
        return frequentQQDao;
    }

    public DownloadHistoryDao getDownloadHistoryDao() {
        return downloadHistoryDao;
    }

    public AccountInfoDao getAccountInfoDao() {
        return accountInfoDao;
    }

    public MyMessageDao getMyMessageDao() {
        return myMessageDao;
    }

}
