package com.etoc.weflow.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.etoc.weflow.dao.FrequentPhone;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FREQUENT_PHONE.
*/
public class FrequentPhoneDao extends AbstractDao<FrequentPhone, String> {

    public static final String TABLENAME = "FREQUENT_PHONE";

    /**
     * Properties of entity FrequentPhone.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Phone_num = new Property(0, String.class, "phone_num", true, "PHONE_NUM");
    };


    public FrequentPhoneDao(DaoConfig config) {
        super(config);
    }
    
    public FrequentPhoneDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FREQUENT_PHONE' (" + //
                "'PHONE_NUM' TEXT PRIMARY KEY NOT NULL );"); // 0: phone_num
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FREQUENT_PHONE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FrequentPhone entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getPhone_num());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FrequentPhone readEntity(Cursor cursor, int offset) {
        FrequentPhone entity = new FrequentPhone( //
            cursor.getString(offset + 0) // phone_num
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FrequentPhone entity, int offset) {
        entity.setPhone_num(cursor.getString(offset + 0));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(FrequentPhone entity, long rowId) {
        return entity.getPhone_num();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(FrequentPhone entity) {
        if(entity != null) {
            return entity.getPhone_num();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
