package com.etoc.weflow.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FREQUENT_PHONE.
 */
public class FrequentPhone {

    private Long id;
    /** Not-null value. */
    private String phone_num;

    public FrequentPhone() {
    }

    public FrequentPhone(Long id) {
        this.id = id;
    }

    public FrequentPhone(Long id, String phone_num) {
        this.id = id;
        this.phone_num = phone_num;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhone_num() {
        return phone_num;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone_num(String phone_num) {
        this.phone_num = phone_num;
    }

}
