package com.etoc.weflow.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MY_MESSAGE.
 */
public class MyMessage {

    /** Not-null value. */
    private String msgid;
    /** Not-null value. */
    private String userid;
    private String type;
    private String picurl;
    private String title;
    private String content;
    private String flowcoins;
    private String time;
    private String pageurl;
    private String productid;
    private String extradata;

    public MyMessage() {
    }

    public MyMessage(String msgid) {
        this.msgid = msgid;
    }

    public MyMessage(String msgid, String userid, String type, String picurl, String title, String content, String flowcoins, String time, String pageurl, String productid, String extradata) {
        this.msgid = msgid;
        this.userid = userid;
        this.type = type;
        this.picurl = picurl;
        this.title = title;
        this.content = content;
        this.flowcoins = flowcoins;
        this.time = time;
        this.pageurl = pageurl;
        this.productid = productid;
        this.extradata = extradata;
    }

    /** Not-null value. */
    public String getMsgid() {
        return msgid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMsgid(String msgid) {
        this.msgid = msgid;
    }

    /** Not-null value. */
    public String getUserid() {
        return userid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPicurl() {
        return picurl;
    }

    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getFlowcoins() {
        return flowcoins;
    }

    public void setFlowcoins(String flowcoins) {
        this.flowcoins = flowcoins;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getPageurl() {
        return pageurl;
    }

    public void setPageurl(String pageurl) {
        this.pageurl = pageurl;
    }

    public String getProductid() {
        return productid;
    }

    public void setProductid(String productid) {
        this.productid = productid;
    }

    public String getExtradata() {
        return extradata;
    }

    public void setExtradata(String extradata) {
        this.extradata = extradata;
    }

}
