package com.cmmobi.railwifi.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAV.
 */
public class Fav {

    private String media_id;
    private int media_type;
    private String name;
    private String img_path;
    private String tag;
    private String color;
    private String introduction;
    private String source;
    private String source_id;
    private String src_path;
    private String director;
    private String actors;
    private String score;

    public Fav() {
    }

    public Fav(String media_id) {
        this.media_id = media_id;
    }

    public Fav(String media_id, int media_type, String name, String img_path, String tag, String color, String introduction, String source, String source_id, String src_path, String director, String actors, String score) {
        this.media_id = media_id;
        this.media_type = media_type;
        this.name = name;
        this.img_path = img_path;
        this.tag = tag;
        this.color = color;
        this.introduction = introduction;
        this.source = source;
        this.source_id = source_id;
        this.src_path = src_path;
        this.director = director;
        this.actors = actors;
        this.score = score;
    }

    public String getMedia_id() {
        return media_id;
    }

    public void setMedia_id(String media_id) {
        this.media_id = media_id;
    }

    public int getMedia_type() {
        return media_type;
    }

    public void setMedia_type(int media_type) {
        this.media_type = media_type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImg_path() {
        return img_path;
    }

    public void setImg_path(String img_path) {
        this.img_path = img_path;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getSource_id() {
        return source_id;
    }

    public void setSource_id(String source_id) {
        this.source_id = source_id;
    }

    public String getSrc_path() {
        return src_path;
    }

    public void setSrc_path(String src_path) {
        this.src_path = src_path;
    }

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public String getActors() {
        return actors;
    }

    public void setActors(String actors) {
        this.actors = actors;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }

}
