package com.cmmobi.railwifi.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MILEAGE_RECORD.
 */
public class MileageRecord {

    private Long id;
    private String starting;
    private String ending;
    private String mileage;
    private String hours;
    private String date;
    private String train_num;
    private String points;

    public MileageRecord() {
    }

    public MileageRecord(Long id) {
        this.id = id;
    }

    public MileageRecord(Long id, String starting, String ending, String mileage, String hours, String date, String train_num, String points) {
        this.id = id;
        this.starting = starting;
        this.ending = ending;
        this.mileage = mileage;
        this.hours = hours;
        this.date = date;
        this.train_num = train_num;
        this.points = points;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStarting() {
        return starting;
    }

    public void setStarting(String starting) {
        this.starting = starting;
    }

    public String getEnding() {
        return ending;
    }

    public void setEnding(String ending) {
        this.ending = ending;
    }

    public String getMileage() {
        return mileage;
    }

    public void setMileage(String mileage) {
        this.mileage = mileage;
    }

    public String getHours() {
        return hours;
    }

    public void setHours(String hours) {
        this.hours = hours;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTrain_num() {
        return train_num;
    }

    public void setTrain_num(String train_num) {
        this.train_num = train_num;
    }

    public String getPoints() {
        return points;
    }

    public void setPoints(String points) {
        this.points = points;
    }

}
