package com.cmmobi.railwifi.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRAVEL_ORDER_INFO.
 */
public class TravelOrderInfo {

    private Long id;
    private String user_id;
    /** Not-null value. */
    private String uuid;
    private String tag;
    private String color;
    private String name;
    private String fullname;
    private String introduction;
    private String line_id;
    private String total_price;
    private String adult_ticket;
    private String child_ticket;
    private String time;
    private String username;
    private String cellphone;
    private String emailaddr;
    private String idcardfnum;
    private String order_time;
    private String order_num;
    private String ispaid;
    private String img;

    public TravelOrderInfo() {
    }

    public TravelOrderInfo(Long id) {
        this.id = id;
    }

    public TravelOrderInfo(Long id, String user_id, String uuid, String tag, String color, String name, String fullname, String introduction, String line_id, String total_price, String adult_ticket, String child_ticket, String time, String username, String cellphone, String emailaddr, String idcardfnum, String order_time, String order_num, String ispaid, String img) {
        this.id = id;
        this.user_id = user_id;
        this.uuid = uuid;
        this.tag = tag;
        this.color = color;
        this.name = name;
        this.fullname = fullname;
        this.introduction = introduction;
        this.line_id = line_id;
        this.total_price = total_price;
        this.adult_ticket = adult_ticket;
        this.child_ticket = child_ticket;
        this.time = time;
        this.username = username;
        this.cellphone = cellphone;
        this.emailaddr = emailaddr;
        this.idcardfnum = idcardfnum;
        this.order_time = order_time;
        this.order_num = order_num;
        this.ispaid = ispaid;
        this.img = img;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /** Not-null value. */
    public String getUuid() {
        return uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getLine_id() {
        return line_id;
    }

    public void setLine_id(String line_id) {
        this.line_id = line_id;
    }

    public String getTotal_price() {
        return total_price;
    }

    public void setTotal_price(String total_price) {
        this.total_price = total_price;
    }

    public String getAdult_ticket() {
        return adult_ticket;
    }

    public void setAdult_ticket(String adult_ticket) {
        this.adult_ticket = adult_ticket;
    }

    public String getChild_ticket() {
        return child_ticket;
    }

    public void setChild_ticket(String child_ticket) {
        this.child_ticket = child_ticket;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getCellphone() {
        return cellphone;
    }

    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    public String getEmailaddr() {
        return emailaddr;
    }

    public void setEmailaddr(String emailaddr) {
        this.emailaddr = emailaddr;
    }

    public String getIdcardfnum() {
        return idcardfnum;
    }

    public void setIdcardfnum(String idcardfnum) {
        this.idcardfnum = idcardfnum;
    }

    public String getOrder_time() {
        return order_time;
    }

    public void setOrder_time(String order_time) {
        this.order_time = order_time;
    }

    public String getOrder_num() {
        return order_num;
    }

    public void setOrder_num(String order_num) {
        this.order_num = order_num;
    }

    public String getIspaid() {
        return ispaid;
    }

    public void setIspaid(String ispaid) {
        this.ispaid = ispaid;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

}
